### ISSUE TITLE
add_remove_distributed_vpool_test fails due to API change: HTTP Error 406: NOT ACCEPTABLE

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/integrationtests#293]
```
======================================================================
ERROR: ci.tests.vpool.vpool_test.TestVPool.add_remove_distributed_vpool_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/OpenvStorage/ci/tests/vpool/vpool_test.py", line 120, in add_remove_distributed_vpool_test
    storagerouters=[local_sr])
  File "/opt/OpenvStorage/ci/tests/general/general_vpool.py", line 91, in add_vpool
    timeout=GeneralVPool.TIMEOUT_ADD_VPOOL)
  File "/opt/OpenvStorage/ci/tests/general/connection.py", line 177, in execute_post_action
    response = urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 406: NOT ACCEPTABLE
```

**Comment by pploegaert** [comment]
Due to missing backend_connection_info ...
https://github.com/openvstorage/framework/commit/ae737690db74e08f3660fa19fa2a9f3ff1328caf

**Comment by pploegaert** [comment]
openvstorage-test-2.7.2-rev.978.71b4e8c
