### ISSUE TITLE
MDS Regression test fails on EE-VIR-3N-199.181-unstable

### ISSUE THREAD

**Issue by ovstmoens** [openvstorage/integrationtests#605]
From _/var/log/ovs/scenario.log_:
```
Traceback (most recent call last):
  File "/opt/OpenvStorage/ci/autotests.py", line 459, in wrapped
    result = func(*args, **kwargs)  # Execute the method
  File "/opt/OpenvStorage/ci/scenarios/vPool/mds_regression/main.py", line 70, in main
    return cls.start_test()
  File "/opt/OpenvStorage/ci/scenarios/vPool/mds_regression/main.py", line 111, in start_test
    api=api)
  File "/opt/OpenvStorage/ci/scenarios/vPool/mds_regression/main.py", line 241, in run_test
    cls._set_mds_safety(1, checkup=True)  # Set the safety to trigger the mds
  File "/opt/OpenvStorage/ci/scenarios/vPool/mds_regression/main.py", line 349, in _set_mds_safety
    storagedriver_config = Configuration.get('/ovs/framework/storagedriver')
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/integrationtests/pull/606
